<a href="https://colab.research.google.com/github/mohnishsachdeva/Binary_Classification_NN/blob/main/Binary_classificaition_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#keras -> tensorflow, caffe, theano and cntk

In [79]:
import pandas as pd
import numpy as np

In [80]:
data = pd.read_csv("drive/My Drive/tumor_data.csv")

In [81]:
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [82]:
data = data.drop(columns=["id","Unnamed: 32"],axis =1)

In [83]:
data['diagnosis'].replace(to_replace = ['B','M'], value = [0,1],inplace = True) 

In [84]:
data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            1        17.99         10.38          122.80     1001.0   
1            1        20.57         17.77          132.90     1326.0   
2            1        19.69         21.25          130.00     1203.0   
3            1        11.42         20.38           77.58      386.1   
4            1        20.29         14.34          135.10     1297.0   
..         ...          ...           ...             ...        ...   
564          1        21.56         22.39          142.00     1479.0   
565          1        20.13         28.25          131.20     1261.0   
566          1        16.60         28.08          108.30      858.1   
567          1        20.60         29.33          140.10     1265.0   
568          0         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    .

In [85]:
data = np.array(data)

In [86]:
np.random.shuffle(data)

In [87]:
data

array([[ 1.     , 15.61   , 19.38   , ...,  0.08568,  0.2683 ,  0.06829],
       [ 0.     , 12.06   , 18.9    , ...,  0.05093,  0.288  ,  0.08083],
       [ 0.     , 12.     , 15.65   , ...,  0.07632,  0.3379 ,  0.07924],
       ...,
       [ 0.     , 11.46   , 18.16   , ...,  0.05509,  0.2208 ,  0.07638],
       [ 1.     , 20.51   , 27.81   , ...,  0.1563 ,  0.2437 ,  0.08328],
       [ 0.     , 11.94   , 20.76   , ...,  0.1155 ,  0.2465 ,  0.09981]])

In [88]:
Y = data[:,0]

In [89]:
Y

array([1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0.

In [90]:
X = data[:,1:]

In [91]:
X

array([[1.561e+01, 1.938e+01, 1.000e+02, ..., 8.568e-02, 2.683e-01,
        6.829e-02],
       [1.206e+01, 1.890e+01, 7.666e+01, ..., 5.093e-02, 2.880e-01,
        8.083e-02],
       [1.200e+01, 1.565e+01, 7.695e+01, ..., 7.632e-02, 3.379e-01,
        7.924e-02],
       ...,
       [1.146e+01, 1.816e+01, 7.359e+01, ..., 5.509e-02, 2.208e-01,
        7.638e-02],
       [2.051e+01, 2.781e+01, 1.344e+02, ..., 1.563e-01, 2.437e-01,
        8.328e-02],
       [1.194e+01, 2.076e+01, 7.787e+01, ..., 1.155e-01, 2.465e-01,
        9.981e-02]])

In [92]:
X.shape

(569, 30)

In [93]:
X_dash = (X-np.mean(X,axis=0))/np.std(X,axis=0)

In [94]:
X_dash

array([[ 0.42111019,  0.0210254 ,  0.33079712, ..., -0.44044795,
        -0.35228097, -0.86757991],
       [-0.5871402 , -0.09067382, -0.63058215, ..., -0.96957221,
        -0.03357819, -0.17266556],
       [-0.60418105, -0.84697064, -0.61863699, ..., -0.58296891,
         0.77369434, -0.26077671],
       ...,
       [-0.75754872, -0.26287679, -0.75703607, ..., -0.90622957,
        -1.12072676, -0.41926595],
       [ 1.81277976,  1.98274299,  1.74774001, ...,  0.63485435,
        -0.750255  , -0.03689681],
       [-0.62122191,  0.34216066, -0.58074201, ...,  0.01360918,
        -0.70495714,  0.87912666]])

In [95]:
from sklearn.model_selection import train_test_split

In [96]:
X,X_test,Y,Y_test= train_test_split(X_dash,Y,test_size=0.1, random_state=42)

In [97]:
print(X.shape)
print(X_test.shape)
print(Y.shape)
print(Y_test.shape)

(512, 30)
(57, 30)
(512,)
(57,)


In [101]:
X_train,X_cv,Y_train,Y_cv= train_test_split(X,Y,test_size=0.15, random_state=42)

In [103]:
print(X_train.shape)
print(X_cv.shape)
print(Y_train.shape)
print(Y_cv.shape)

(435, 30)
(77, 30)
(435,)
(77,)


In [117]:
from keras.layers import InputLayer,Dense, BatchNormalization
from keras.models import Sequential

In [118]:
from keras.regularizers import l2
from keras.optimizers import Adam

In [125]:
def build_network():

  network = Sequential()
  
  network.add(InputLayer(input_shape=(X_train.shape[1],),))
 
  #kernel_initializer = connection matrix of theta's
  network.add(Dense(units=X_train.shape[1],activation="relu",kernel_initializer="glorot_normal"))
  
  network.add(BatchNormalization())
  
  # network.add(Dense(units=X_train.shape[1],activation="relu",kernel_initializer="glorot_normal",kernel_regularizer=l2()))
  
  # network.add(BatchNormalization())
  
  network.add(Dense(units=1,activation="sigmoid", kernel_initializer="glorot_normal"))

  return network

In [126]:
network = build_network()

In [127]:
network.compile(optimizer="adam",loss="binary_crossentropy",metrics = ["accuracy"])

In [128]:
performance_history = network.fit(x=X_train,y=Y_train,batch_size=5,epochs=50 ,validation_data=(X_cv,Y_cv))

Epoch 1/50
87/87 [==============================] - 1s 4ms/step - loss: 0.5870 - accuracy: 0.6644 - val_loss: 0.3363 - val_accuracy: 0.9091
Epoch 2/50
87/87 [==============================] - 0s 2ms/step - loss: 0.3081 - accuracy: 0.8667 - val_loss: 0.2384 - val_accuracy: 0.9221
Epoch 3/50
87/87 [==============================] - 0s 2ms/step - loss: 0.2863 - accuracy: 0.8759 - val_loss: 0.2028 - val_accuracy: 0.9481
Epoch 4/50
87/87 [==============================] - 0s 3ms/step - loss: 0.2471 - accuracy: 0.8943 - val_loss: 0.1974 - val_accuracy: 0.9481
Epoch 5/50
87/87 [==============================] - 0s 2ms/step - loss: 0.2487 - accuracy: 0.9103 - val_loss: 0.1715 - val_accuracy: 0.9481
Epoch 6/50
87/87 [==============================] - 0s 2ms/step - loss: 0.2755 - accuracy: 0.8713 - val_loss: 0.1687 - val_accuracy: 0.9610
Epoch 7/50
87/87 [==============================] - 0s 2ms/step - loss: 0.2495 - accuracy: 0.8943 - val_loss: 0.1482 - val_accuracy: 0.9481
Epoch 8/50
87/87 [==

In [129]:
network.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 30)                930       
                                                                 
 batch_normalization_1 (Batc  (None, 30)               120       
 hNormalization)                                                 
                                                                 
 dense_5 (Dense)             (None, 1)                 31        
                                                                 
Total params: 1,081
Trainable params: 1,021
Non-trainable params: 60
_________________________________________________________________


In [130]:
network.evaluate(x=X_test, y=Y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.0945 - accuracy: 0.9825


[0.09451834857463837, 0.9824561476707458]